### ISSUE TITLE
Request to use sprites

### ISSUE THREAD

**Issue by Anonymous941** [PK-Remake/Mother-Remake#2]
I know that it says that the sprites are exclusively for this project, but I'm working on an open-source complete recreation from scratch of MOTHER 1 that looks like MOTHER 3 in Godot and need sprites.  The original MOTHER 1 sprites are too basic to look like MOTHER 3, and I don't have anyone who can make sprites for me.

Can I use these sprites on that project?

**Comment by Anonymous941** [comment]
@livvy94

**Comment by Messianic** [comment]
No.

**Comment by Anonymous941** [comment]
I already got that response on Discord, and forgot to close this issue
